services:
  cypress-test:
    container_name: cypress-test
    profiles: [ '', 'tests' ]
    build:
      dockerfile: cypress.dockerfile
    environment:
      CYPRESS_BASE_URL: 'http://mnestix-browser:3000'
      CYPRESS_AAS_REPO_API_URL: 'http://mnestix-api:5064/repo'
      CYPRESS_SUBMODEL_REPO_API_URL: 'http://mnestix-api:5064/repo'
      CYPRESS_MNESTIX_BACKEND_API_URL: 'http://mnestix-api:5064'
      CYPRESS_AAS_DISCOVERY_API_URL: 'http://mnestix-api:5064/discovery'
      ELECTRON_ENABLE_LOGGING: 1
      SPLIT: ${SPLIT:-1}
      SPLIT_INDEX: ${SPLIT_INDEX:-0}
    command: run
    volumes:
      - ./cypress/:/cypress_Tests/cypress
      - ./cypress.config.ts:/cypress_Tests/cypress.config.ts
      - ./cypress-artifacts/screenshots:/cypress_Tests/cypress/screenshots
      - ./cypress-artifacts/videos:/cypress_Tests/cypress/videos
      # esm compatibility
      - ./tsconfig.json:/cypress_Tests/tsconfig.json
    depends_on:
      mnestix-browser:
        condition: service_started
      mnestix-api:
        condition: service_started
      aas-environment:
        condition: service_started
      keycloak:
        condition: service_healthy # keycloak needs to be healthy before tests
    networks:
      - mnestix-network

  mnestix-browser:
    image: mnestix/mnestix-browser:latest
    environment:
      AAS_REPO_API_URL: 'http://mnestix-api:5064/repo'
      SUBMODEL_REPO_API_URL: 'http://mnestix-api:5064/repo'
      DISCOVERY_API_URL: 'http://mnestix-api:5064/discovery'
      MNESTIX_BACKEND_API_URL: 'http://mnestix-api:5064'
      AUTHENTICATION_FEATURE_FLAG: 'true'
      NEXTAUTH_URL: 'http://mnestix-browser:3000/'
      KEYCLOAK_ENABLED: 'true'
      KEYCLOAK_CLIENT_ID: 'mnestix-browser-client-demo'
      KEYCLOAK_ISSUER: 'http://keycloak:8080'
      KEYCLOAK_REALM: "Mnestix"

  keycloak:
    profiles: [ '', 'tests' ]
    image: keycloak/keycloak:24.0.4
    container_name: keycloak
    volumes:
      - ./docker-compose/data/keycloak/realm/Mnestix-realm.json:/opt/keycloak/data/import/realm-config.json
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_DEBUG: 'true'
      KC_SPI_INITIALIZER_ISSUER_BASE_URI: http://keycloak:8080
      KC_HEALTH_ENABLED: 'true'
    command: [ 'start-dev', '--import-realm' ]
    healthcheck:
      test: #keycloak has no curl in image
        [
          'CMD-SHELL',
          "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'",
        ]
      interval: 30s
      timeout: 5s
      retries: 20

    networks:
      - mnestix-network
